name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com" 
          git config --global user.name "Github Action"

      - name: Apply patches
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" applyPatches --stacktrace --no-daemon

      - name: Create MojmapPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" createMojmapPaperclipJar --stacktrace --no-daemon

      - name: Rename Paperclip Jar
        run: mv build/libs/NorsPaper-paperclip-1.21.1-R0.1-SNAPSHOT-mojmap.jar ./norspaper-1.21.1.jar

      - name: Upload NorsPaper
        uses: actions/upload-artifact@v4
        with:
          name: NorsPaper 1.21.1
          path: ./norspaper-1.21.1.jar

      - name: Release NorsPaper
        if: github.event_name != 'pull_request'
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "NorsPaper 1.21.1"
          automatic_release_tag: "ver-1.21.1"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "./norspaper-1.21.1.jar"
          prerelease: false