name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: gradle

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com" 
          git config --global user.name "Github Action"

      - name: Apply patches
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" applyPatches --stacktrace --no-daemon

      - name: Create MojmapPaperclipJar
        run: ./gradlew -Dorg.gradle.jvmargs="-Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true --add-modules jdk.incubator.vector" createMojmapPaperclipJar --stacktrace --no-daemon

      - name: Rename Paperclip Jar
        run: mv build/libs/NorsPaper-paperclip-1.21.1-R0.1-SNAPSHOT-mojmap.jar ./norspaper-1.21.1.jar

      - name: Upload NorsPaper
        uses: actions/upload-artifact@v4.6.0
        with:
          name: NorsPaper 1.21.1
          path: ./norspaper-1.21.1.jar

      - name: Remove Existing Tag (if any)
        run: |
          git tag -d ver-1.21.1 || true
          git push origin :refs/tags/ver-1.21.1 || true

      - name: Create GitHub Release
        if: github.event_name != 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          artifacts: norspaper-1.21.1.jar
          tag: "ver-1.21.1"
          name: "NorsPaper 1.21.1"
          prerelease: false
          token: "${{ secrets.GITHUB_TOKEN }}"